### ISSUE TITLE
writedata.jl hangs

### ISSUE THREAD

**Issue by quinnj** [davidanthoff/csv-comparison#1]
Haven't had a chance to figure out what exactly is going wrong, but once I got all the packages installed, calling writedata.jl ran for some 45 minutes or so before I finally killed it. Not sure if you ran into something similar.

**Comment by davidanthoff** [comment]
Can you try again? I just pushed a new version.

The old version also wrote CSV files with 10 million rows for all combinations, and that actually took a very long time. The benchmark script doesn't actually read those because I ran into out of memory situations with that, so now I've modified the write script to also not write those 10 million row files.

I do hope to reenable the 10 million row case at some point. Probably easiest by running all benchmarks in sub processes, like it is done for the julia 0.6 runs right now. That way we could be sure that memory gets cleaned up after each benchmark and maybe that will help...

**Comment by davidanthoff** [comment]
Closing for now, as I think this is all working, it just might take a while. Please do let me know if there are other issues!
